name: Tests

on:
  push:
    branches: [main, Development]
  pull_request:
    branches: [main, Development]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.6
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=5

      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=5

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Bench CLI
        run: |
          pip install --upgrade pip
          pip install frappe-bench

      - name: Init Bench & Install Frappe
        run: |
          bench init --skip-assets --skip-redis-config-generation \
            --frappe-path https://github.com/frappe/frappe \
            --frappe-branch version-15 frappe-bench
          cd frappe-bench
          bench setup requirements --dev

      - name: Get Apps (ERPNext + Custom App)
        run: |
          cd frappe-bench
          bench get-app --branch version-15 erpnext https://github.com/frappe/erpnext
          bench get-app pos_restaurant_itb $GITHUB_WORKSPACE

      - name: Setup Site
        run: |
          cd frappe-bench
          bench new-site site1.local --mariadb-root-password root --admin-password admin \
            --install-app erpnext
          bench --site site1.local install-app pos_restaurant_itb

      - name: Run Tests
        run: |
          cd frappe-bench
          bench --site site1.local set-config allow_tests true
          bench --site site1.local run-tests --app pos_restaurant_itb

      - name: Show Logs on Failure
        if: failure()
        run: |
          cd frappe-bench
          cat sites/site1.local/logs/frappe.log || true
          cat sites/site1.local/logs/tests.log || true
